services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: password
      POSTGRES_DB: typeormstudy
    ports:
      - "5633:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data